RDBMS PROGRAM 15-ITEM UPDATION USING PROCEDURE

CREATE TABLE SHOP(ITEM_ID INT PRIMARY KEY,ITEM_NAME CHAR(25),PRICE NUMBER(5,2),QUANTITY INT);

INSERT INTO SHOP VALUES(101,'CLOSUP',24,50);
INSERT INTO SHOP VALUES(102,'MEDIMIX',30,150);
INSERT INTO SHOP VALUES(103,'SUGAR',39,65);
INSERT INTO SHOP VALUES(104,'AVT',45,100);
INSERT INTO SHOP VALUES(105,'PEN',10,80);

CREATE OR REPLACE PROCEDURE UPDATEDATA(IID IN INT,QUA IN INT) IS

BEGIN
    UPDATE SHOP SET QUANTITY=QUA WHERE ITEM_ID=IID;
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('ITEM NOT FOUND');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ITEM QUANTITY UPDATED');
    END IF;
END;

DECLARE
    ITEMID INT;
    QTY INT;
BEGIN
    ITEMID:=&ITEM_ID;
    QTY:=&NEW_QUANTITY;
    UPDATEDATA(ITEMID,QTY);
END;

SELECT * FROM SHOP;