RDBMS PROGRAM 13-MARKS

CREATE TABLE MARKS(
                  REG_NO INT PRIMARY KEY,
                  NAME CHAR(20),
                  SUB_1 INT,
                  SUB_2 INT,
                  SUB_3 INT,
                  SUB_4 INT,
                  TOTAL INT,
                  AVG_SCORE NUMBER(5,2),
                  GRADE CHAR(2)
                  );
                  
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1001,'JUNAID',95,75,54,96); 
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1002,'HAKEEM',55,58,82,64);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1003,'SALMAN',41,95,50,62);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1004,'JIFRI',92,84,94,96);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1005,'THASNI',40,36,42,53);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1006,'NASIRA',50,66,32,73);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1007,'AKSHAY',56,63,23,46);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1008,'GOPAL',70,66,72,93);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1009,'RANJITH',45,56,55,54);
INSERT INTO MARKS(REG_NO,NAME,SUB_1,SUB_2,SUB_3,SUB_4)VALUES(1010,'SHEBIN',66,78,46,89);

DECLARE
    REGNO MARKS.REG_NO%TYPE;
    SUB1 MARKS.SUB_1%TYPE;
    SUB2 MARKS.SUB_2%TYPE;
    SUB3 MARKS.SUB_3%TYPE;
    SUB4 MARKS.SUB_4%TYPE;
    TOT MARKS.TOTAL%TYPE;
    
    AVRG MARKS.AVG_SCORE%TYPE;
    
    CURSOR C_MARKS IS SELECT REG_NO,SUB_1,SUB_2,SUB_3,SUB_4 FROM MARKS;

BEGIN
    OPEN C_MARKS;
    LOOP
        FETCH C_MARKS INTO REGNO,SUB1,SUB2,SUB3,SUB4;
        EXIT WHEN C_MARKS%NOTFOUND;
        TOT:=SUB1+SUB2+SUB3+SUB4;
        AVRG:=TOT/4;
        UPDATE MARKS SET TOTAL=TOT,AVG_SCORE=AVRG WHERE REG_NO=REGNO;
    
        IF AVRG>=90 AND AVRG<=100 THEN
            UPDATE MARKS SET GRADE='A' WHERE REG_NO=REGNO;
        ELSIF AVRG>=75 AND AVRG<=89 THEN
            UPDATE MARKS SET GRADE='B' WHERE REG_NO=REGNO;
        ELSIF AVRG>=60 AND AVRG<=74 THEN
            UPDATE MARKS SET GRADE='C' WHERE REG_NO=REGNO;
        ELSIF AVRG>=50 AND AVRG<=59 THEN
            UPDATE MARKS SET GRADE='D' WHERE REG_NO=REGNO;
        ELSIF AVRG<50 THEN 
            UPDATE MARKS SET GRADE='F' WHERE REG_NO=REGNO;
        END IF;
    END LOOP;
    CLOSE C_MARKS;
END;


SELECT * FROM MARKS ORDER BY AVG_SCORE ASC;